### ISSUE TITLE
unique python code for beginner

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/python-learning-codes#25]
just submit unique code

**Comment by vilasrhegde** [comment]
@hariom20singh can you assign me this problem? I'd like to add the problem zero sum subarray using Python

**Comment by 035pratheeksha** [comment]
@hariom20singh can you assign me this problem? I would like to add rock paper scissor game 
using Python

**Comment by MSVelan** [comment]
@hariom20singh I would like to add compressing images using python. Can you please assign it to me?

**Comment by yashqwerty1** [comment]
assign me this problem
i will add some good Intermediate and fun programs + Beginners too.

**Comment by vilasrhegde** [comment]
@hariom20singh I've sent you the PR for Zero Sum Subarray problem. Can you merge it? thanks

**Comment by 035pratheeksha** [comment]
I've sent you the PR for rock paper scissor game. Could you please merge it?

**Comment by yashqwerty1** [comment]
I have sent you the PR for Number Guessing Game. Can you merge it ?
More Good Ones are coming with GUI.

**Comment by MSVelan** [comment]
I have sent the PR for compressing image using python. Please consider merging it.

**Comment by SamagraAg** [comment]
Hii @hariom20singh assign me this . I would add some python projects and games made by me.

**Comment by md-tausif09** [comment]
please assign me

**Comment by MSVelan** [comment]
Hey, I would like to add program for live weather notification from desktop. Can you assign me?
