### ISSUE TITLE
submit code for hacktoberfest

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/python-learning-codes#34]

**Comment by DivvSaxena** [comment]
which code we can to add?

**Comment by DivvSaxena** [comment]
and can we write code in java

**Comment by lumi232** [comment]
I would like to contribute can you pls assign me this ?

**Comment by HarshAggarwal1** [comment]
I would like to contribute, please assign me this

**Comment by Tanucode** [comment]
I would like to contribute ,please assign this to me.

**Comment by munish0838** [comment]
Hi, I would contribute some code for Hacktoberfest
