### ISSUE TITLE
Any python code for data structure

### ISSUE THREAD

**Issue by hariom20singh** [hariom20singh/python-learning-codes#5]

**Comment by Pavan49719** [comment]
Hey @hariom20singh, I would like to work on this issue.  I can add linear search code in Python.

**Comment by vilasrhegde** [comment]
Hey @hariom20singh , I want to add Binary Search. Can I work on this issue?

**Comment by Ashpreetwadhwa** [comment]
hey @hariom20singh i can work on sorting algorithms

**Comment by Ashpreetwadhwa** [comment]
i can work on more such algorithms

**Comment by Shubh942** [comment]
Hey @hariom20singh please assign me. I want to add the concept of linked list in this task.

**Comment by vilasrhegde** [comment]
@hariom20singh  can you look into my work? about binary search using python?

**Comment by NNRepos** [comment]
hey, i would like to add BFS on a tree code in python, please assign me if you're interested 😄

**Comment by himanshu17-2000** [comment]
i want to implement dijkstra's algorithm can i work upon this

**Comment by RushikeshMali05** [comment]
hi, I want to work on some of the popular linked list questions, can you please assign me?

**Comment by 035pratheeksha** [comment]
can you please assign this to me?

**Comment by Arika008** [comment]
@hariom20singh Please check my PR #58

**Comment by HarshAggarwal1** [comment]
Hey @hariom20singh, Please check my PR in the Python DSA part; I have added two sorting algos and one advanced implementation of the linked list

**Comment by ankitkumar0622** [comment]
can you please assign this to me?

**Comment by Rising-tech** [comment]
Hey, I would like to contribute. Can you please assigned me?

**Comment by HarshAggarwal1** [comment]
Hi @hariom20singh Please accept my PR #89

**Comment by shahrushi2003** [comment]
Please assign this issue to me. I can add some very useful sorting algos like merge sort, quick sort, count sort, etc.

**Comment by munish0838** [comment]
Hi, I would like to add some leetcode solutions to this repo
